Spanned holes: threading positions through holes (#1085)
Every hole is now internally associated with a span which is printed
when the hole is encountered:
```sh
$ for BACKEND in chez-callcc llvm js; do effekt hole.effekt --backend $BACKEND; done
```

```log
# Chez
Exception: hole.effekt:8:15: not implemented yet
[error] Process exited with non-zero exit code 255.

# LLVM
PANIC: hole.effekt:8:15: not implemented yet
[error] Process exited with non-zero exit code 1.

# JS
.../out/hole.js:208
    else throw e
         ^
hole.effekt:8:15: not implemented yet
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v22.16.0
[error] Process exited with non-zero exit code 1.
```